Parameters:
  LogBucketName:
    Description: Name for the logs bucket
    Type: String

Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LogBucketName
      AccessControl: LogDeliveryWrite
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  IpAddressTrackingTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ip_address_access_counts
      AttributeDefinitions:
        -
          AttributeName: "ip_address"
          AttributeType: "S"
        -
          AttributeName: "site"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "ip_address"
          KeyType: "HASH"
        -
          AttributeName: "site"
          KeyType: "RANGE"

      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
Outputs:
  LogBucketName:
    Value: !Ref LogBucket
    Description: Logging Bucket Name
    Export:
      Name: LogBucket
